CREATE DATABASE IF NOT EXISTS IMOVELGUIDE;

USE IMOVELGUIDE;

CREATE TABLE IF NOT EXISTS TBL_CORRETORES (
    ID_CORRETOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    CRECI VARCHAR(10) UNIQUE NOT NULL
);